CREATE TABLE users(
"id" SERIAL NOT NULL PRIMARY KEY,
"name" TEXT NOT NULL,
"email" TEXT NOT NULL UNIQUE,
"password" TEXT NOT NULL UNIQUE,
"createdAt" DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE sessions(
"id" SERIAL NOT NULL PRIMARY KEY,
"token" TEXT NOT NULL UNIQUE,
"userId" INTEGER NOT NULL REFERENCES users(id),
"createdAt" DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE urls(
id SERIAL NOT NULL PRIMARY KEY,
"originalUrl" TEXT NOT NULL,
"shortenedUrl" TEXT NOT NULL UNIQUE,
"visitsCounter" INTEGER NOT NULL DEFAULT '0',
"userId" INTEGER NOT NULL REFERENCES users(id),
"createdAt" DATE NOT NULL DEFAULT CURRENT_DATE
);